name: ssgc
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  get: ^4.6.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  otp_text_field: ^1.1.3
  flutter_screenutil: ^5.7.0
  google_fonts: ^5.1.0
  scroll_snap_list: ^0.9.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
